# Generated by Django 2.2.2 on 2019-07-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=120)),
                ('Comment', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='AboutUsSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s1/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=120)),
                ('COMPANY', models.CharField(max_length=120)),
                ('TELEPHONE', models.CharField(max_length=120)),
                ('EMAIL', models.EmailField(max_length=120)),
                ('MESSAGE', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('NAME',),
            },
        ),
        migrations.CreateModel(
            name='HomeS1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s1/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='HomeS2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Name2', models.CharField(max_length=120)),
                ('Text', models.CharField(max_length=300)),
                ('Image', models.ImageField(upload_to='s2/')),
            ],
        ),
        migrations.CreateModel(
            name='Homes3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s3/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='Homeslide3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='slider3/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='slider/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='HomeSlider2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Name2', models.CharField(max_length=120)),
                ('Text', models.CharField(max_length=300)),
                ('Image', models.ImageField(upload_to='slider2/')),
            ],
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=120)),
                ('COMPANY', models.CharField(max_length=120)),
                ('TELEPHONE', models.CharField(max_length=120)),
                ('EMAIL', models.EmailField(max_length=120)),
                ('MESSAGE', models.CharField(max_length=300)),
                ('IMAGE', models.ImageField(blank=True, upload_to='joinus')),
            ],
            options={
                'ordering': ('NAME',),
            },
        ),
        migrations.CreateModel(
            name='JoinUsSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s1/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s1/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='ProductSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s1/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='ProductSlider1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s1/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='SpecialtiesSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s1/')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='s1/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductCategory')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
          migrations.CreateModel(
            name='BecomeDistributer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=120)),
                ('COMPANY', models.CharField(max_length=120)),
                ('TELEPHONE', models.CharField(max_length=120)),
                ('EMAIL', models.EmailField(max_length=120)),
                ('MESSAGE', models.CharField(max_length=300)),
                ('IMAGE', models.ImageField(blank=True, upload_to='distributer')),
            ],
            options={
                'ordering': ('NAME',),
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('quantity', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=120)),
                ('Item_number', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='ProductsImages/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductCategory')),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
    ]
