# Generated by Django 2.1.4 on 2018-12-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeslide3'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Name2', models.CharField(max_length=120)),
                ('Text', models.CharField(max_length=300)),
                ('Image', models.ImageField(upload_to='slider2/')),
            ],
        ),
    ]
