# Generated by Django 2.1.5 on 2019-01-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181228_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Artical',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
