# Generated by Django 2.1.5 on 2019-02-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190118_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=120)),
                ('COMPANY', models.CharField(max_length=120)),
                ('TELEPHONE', models.CharField(max_length=120)),
                ('EMAIL', models.EmailField(max_length=120)),
                ('MESSAGE', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=120)),
                ('COMPANY', models.CharField(max_length=120)),
                ('TELEPHONE', models.CharField(max_length=120)),
                ('EMAIL', models.EmailField(max_length=120)),
                ('MESSAGE', models.CharField(max_length=300)),
            ],
        ),
    ]
