# Generated by Django 2.1.5 on 2019-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190214_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='TELEPHONE',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='TELEPHONE',
            field=models.IntegerField(blank=True),
        ),
    ]
