# Generated by Django 2.1.5 on 2019-02-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190214_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='MESSAGE',
            new_name='Message',
        ),
    ]
