# Generated by Django 2.1.5 on 2019-02-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190225_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='MESSAGE',
        ),
    ]
