# Generated by Django 2.1.5 on 2019-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190225_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='TELEPHONE',
            field=models.IntegerField(blank=True, max_length=12),
        ),
    ]
