# Generated by Django 2.1.5 on 2019-03-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190304_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='TELEPHONE',
            field=models.IntegerField(blank=True),
        ),
    ]
