# Generated by Django 2.1.5 on 2019-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190306_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='TELEPHONE',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
