# Generated by Django 2.1.5 on 2019-03-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190306_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinus',
            old_name='COMPANY',
            new_name='FIRST_NAME',
        ),
        migrations.RenameField(
            model_name='joinus',
            old_name='NAME',
            new_name='LAST_NAME',
        ),
    ]
