# Generated by Django 2.1.5 on 2019-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190306_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='TELEPHONE',
            field=models.CharField(max_length=20),
        ),
    ]
