# Generated by Django 2.1.5 on 2019-03-06 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190306_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='TELEPHONE',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000000000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
